### ISSUE TITLE
Not sending messages to discord

### ISSUE THREAD

**Issue by finalblu** [Selly/selly-discord-bot#5]
Having a similar issue to #2 , this time on v0.0.4.
Already have the latest version of GoLang, using windows.exe
```
[  info ] 2018/02/02 00:40:23 Bot started
[  info ] 2018/02/02 00:43:30 {6f2bb957-f64c-43c6-9ad6-386dafafbddf [redacted] sample@webhook-email.com 123.123.123.123 US  4.99 USD PayPal 0 0  <nil> <nil>  0  }
[  info ] 2018/02/02 00:43:53 {95563a3a-79d5-459d-81a8-56b06fbf36cf [redacted] sample@webhook-email.com 123.123.123.123 US  4.99 USD PayPal 0 0  <nil> <nil>  0  }
```
(sorry I can't provide any more information)

**Comment by Doc1337** [comment]
Just use the older version, it works fine, or check if the bot has access to embed messages.

**Comment by finalblu** [comment]
downgrading to 0.0.3 fixed it

**Comment by Sexual** [comment]
This is not maintained and is archived. It was originally created to demonstrate how simple it can be to integrate our webhook system into something like Discord.

If you want Discord notifications, just create a [discord webhook](https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks) and set this URL as your product's webhook URL in Selly. We'll handle everything else.
